#!/bin/bash
VARIABLES=("NEXT_PUBLIC_PLAYER_PARSER_URL" "NEXT_PUBLIC_API_URL" "NEXT_PUBLIC_SHARE_PREFIX" "NEXT_PUBLIC_ANILIBRIA_API_URL" "NEXT_PUBLIC_TORAPI_API_URL")

NEXT_PUBLIC_PLAYER_PARSER_URL=${NEXT_PUBLIC_PLAYER_PARSER_URL:-""}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-"/api/proxy"}
NEXT_PUBLIC_SHARE_PREFIX=${NEXT_PUBLIC_SHARE_PREFIX:-"https://anixart-app.com"}
NEXT_PUBLIC_ANILIBRIA_API_URL=${NEXT_PUBLIC_ANILIBRIA_API_URL:-"https://anilibria.top"}
NEXT_PUBLIC_TORAPI_API_URL=${NEXT_PUBLIC_TORAPI_API_URL:-"https://torapi.vercel.app"}

find /app/public /app/.next -type f -name "*.js" |
while read file; do
    for VAR in "${VARIABLES[@]}"; do
        sed -i "s|BAKED_$VAR|${!VAR}|g" "$file"
    done
done
